### ISSUE TITLE
Port to 1.18.2

### ISSUE THREAD

**Issue by rmr4k** [Roundaround/mc-fabric-armor-stands#1]
Hello, could you please tell me if it's possible to port Armor Stands to version 1.18.2? Will you do the porting?

**Comment by Roundaround** [comment]
If I do port it to 1.18.2 it probably won't be for a long time. It's a lot of work to maintain multiple versions and I do this as a hobby, so if I was going to do it I'd wait for a good stable version of the mod, then port it back and never touch the 1.18.2 version again.

That being said, this and all my mods are licensed under MIT, which is fully permissible. If you or anyone else wants to port and rehost it, you are perfectly allowed to do so!
