### ISSUE TITLE
[modrinth] include 1.20.1 in supported

### ISSUE THREAD

**Issue by ColonelGerdauf** [Roundaround/mc-fabric-armor-stands#10]
Right now, the mod is listed as supporting 1.20. That may work for standalone situations, but launchers such as Prism are quite strict about version support. And in the case of launchers, 1.20 is not 1.20.1. Therefore, Prism will complain about "armor stands" being incompatible whenever one attempts mod updates.

It would be helpful to add in support for 1.20.1 in the Modrinth page, in context of version 1.2.1.

**Comment by Roundaround** [comment]
Done. Sorry for the delay! Life has been crazy :)
