### ISSUE TITLE
Essential support?

### ISSUE THREAD

**Issue by Salamandraatra** [Roundaround/mc-fabric-armor-stands#17]
This mod for some reason disables the essentials mod

**Comment by Roundaround** [comment]
I'm going to assume you're referring to the microtransactions mod, in which case I don't think I can help you. I did some investigating and can't figure out where the compatibility issue is, but I assume it has something to do with Essential's very VERY non-standard and incredibly convoluted mod loading infrastructure. I was going to report the issue on their GitHub but it seems like they don't have the issue tracker enabled. I'm sorry but I'm not sure what else I can do for you.
