### ISSUE TITLE
essentials mod can't be used

### ISSUE THREAD

**Issue by Phoenix720** [Roundaround/mc-fabric-armor-stands#18]
When loading a game with essentials mod and armor stands it will no longer be able to be used or seen in a mod menu and you will not be able to even see it in the key binds.

**Comment by OmriPH** [comment]
From the developer on #17:
> I'm going to assume you're referring to the microtransactions mod, in which case I don't think I can help you. I did some investigating and can't figure out where the compatibility issue is, but I assume it has something to do with Essential's very VERY non-standard and incredibly convoluted mod loading infrastructure. I was going to report the issue on their GitHub but it seems like they don't have the issue tracker enabled. I'm sorry but I'm not sure what else I can do for you.

**Comment by Roundaround** [comment]
Should be fixed with 2.0.1 versions for 1.20.5 up through 1.21.4! Check out the new versions on Modrinth!
