### ISSUE TITLE
port to 1.19.3

### ISSUE THREAD

**Issue by MIPOHBOPOHIH** [Roundaround/mc-fabric-armor-stands#2]
I really liked the functionality of the mod, and it would be interesting to know - in how long approximately can the mod be updated to 1.19.3?

**Comment by Roundaround** [comment]
I'll be releasing a 1.19.3 version when it leaves beta. Until I'm locked in on the initial version, I'm gonna be changing a lot of things quickly and don't want to have to maintain multiple versions of the mod.

Currently I don't have a real time estimate for this. It could be anywhere from a few days to a few weeks from now.

**Comment by Roundaround** [comment]
1.19.3 (and 1.19.4) support is out! Check it out at https://modrinth.com/mod/armor-stands
