### ISSUE TITLE
Cant press "Q" in the inventory to drop items. (only when this mod is being used)

### ISSUE THREAD

**Issue by Z3d04** [Roundaround/mc-fabric-armor-stands#5]
idk, i cant press q when i have the mod active, is there a setting i have missed or something?

**Comment by Z3d04** [comment]
i cant close the inventory with "E" ether btw

**Comment by Roundaround** [comment]
This sounds like either some kind of mod incompatibility or your keybinds are clashing or something. Neither I nor my several playtesters can replicate.

I would check your keybinds aren't colliding, and watch the logs on startup for any errors. They're usually pretty descriptive of which mod they're coming from.
